<?php
$arr = [
  "Support",
  "Account Settings",
  "Sign Out",
  "add listing",
  "Home",
  "Quick Links",
  "Support Links",
  "Contact Us",
  "Copyright",
  "All Rights Reserved",
  "subscribe",
  "Enter your mail",
  "Send a massage",
  "Phone",
  "Email",
  "Address",
  "Your Name",
  "E-mail Address",
  "Your Subject",
  "Your Massage",
  "What are you looking for",
  "search",
  "All Category",
  "All Locations",
  "Or browse the highlights",
  "Listings",
  "Browse All Different",
  "Categories",
  "reviews",
  "view more",
  "learn more",
  "Package Expiration",
  "Listing Allowed",
  "Package Renew not Available",
  "Package Renew Available",
  "Whatsapp chat SDK not Available",
  "Whatsapp chat SDK Available",
  "Messenger chat SDK not Available",
  "Messenger chat SDK Available",
  "No seo Allowed per listing",
  "SEO Allowed per listing",
  "No business hour Allowed per listing",
  "Business hour Allowed per listing",
  "No amenity Allowed per listing",
  "Unlimited amenity Allowed per listing",
  "amenity Allowed per listing",
  "No video Allowed per listing",
  "video Allowed per listing",
  "No image Allowed per product",
  "Unlimited image Allowed per product",
  "image Allowed per product",
  "No product Allowed per listing",
  "Unlimited product Allowed per listing",
  "product Allowed per listing",
  "No category allowed per listing",
  "category allowed per listing",
  "image Allowed per listing",
  "Unlimited image Allowed per listing",
  "No image Allowed per listing",
  "Serach",
  "Search here",
  "social share",
  "Recent Post",
  "Filters",
  "Listing name",
  "Filter by",
  "Select Location",
  "Select Category",
  "Filter by Ratings",
  "View details",
  "Description",
  "Amenities",
  "Video",
  "Reviews",
  "Add Review",
  "Writing great reviews may help others discover the places that are just apt for them",
  "Type here",
  "submit",
  "Customer Feedback",
  "5 Stars",
  "4 Stars",
  "3 Stars",
  "2 Stars",
  "1 Stars",
  "Member since",
  "view profile",
  "Send a Message",
  "Full Name",
  "Send Message Now",
  "Contact Seller",
  "Opening Hours",
  "Closed",
  "Claim Now",
  "Claim This Business",
  "start chat",
  "Related Listings",
  "Copy Profile",
  "Listing",
  "Total Views",
  "Follower",
  "Following",
  "Send Message Now",
  "Listings",
  "Welcome back!",
  "Hey Enter your details to get sign in to your account",
  "Email Or Username",
  "Remember me",
  "Forgot password",
  "Log in",
  "Don't have an account",
  "Create account",
  "Already have an account?",
  "Login Here",
  "sign up",
  "Hey Enter your details to get sign in to your account",
  "Recover password",
  "Enter your email to recover the password",
  "Enter verification code that send to your email",
  "Resend code",
  "Sms Verification",
  "My Profile",
  "Sign Out",
  "Clear all notifications",
  "You have no notifications",
  "Dashboard",
  "My Packages",
  "My Listings",
  "WishList",
  "Package",
  "No. of listing",
  "Purchased Date",
  "Expired Date",
  "Purchased",
  "Try Free",
  "Validity",
  "Status",
  "Action",
  "No Data Found",
  "Filter",
  "Search",
  "Purchase Date",
  "Expired Date",
  "Active",
  "Expired",
  "Pending",
  "Approved",
  "Cancelled",
  "Status",
  "Payment History",
  "Payment History For",
  "Payment History",
  "Search for Transaction ID",
  "Transaction ID",
  "Remark",
  "Date",
  "Package Renew Information",
  "Close",
  "All Listings",
  "Pending",
  "Approved",
  "Rejected",
  "Are you sure want to delete this",
  "Add Listing",
  "Create Listing",
  "Category",
  "All Category",
  "Analytics",
  "From Date",
  "Reviews of",
  "Filter By User",
  "Rating",
  "Select Rating",
  "To Date",
  "My WishList",
  "WishList",
  "Transactions",
  "My Transactions",
  "Transaction ID",
  "Remark",
  "Choose Date",
  "Support Ticket",
  "Create Ticket",
  "Open Ticket",
  "Answered Ticket",
  "Replied Ticket",
  "Closed Ticket",
  "Create Ticket",
  "Create Form",
  "Filter Listing",
  "Location",
  "Packages",
  "Filter Package",
  "Select Validity",
  "Payment History",
  "Filter Payment History",
  "Enquiries",
  "Search Here",
  "Ticket No",
  "Do you really want to make this claim",
  "If you can\'t prove it, you should face a fine",
  "Claim Now",
  "Sample File Fields",
  "Data Collection Form",
];
return $arr;
